### ISSUE TITLE
Unit Conversion Error: ACH

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/wex#10]
When opening an OS 1.14.0 `eplusout.sql` file.

![image](https://user-images.githubusercontent.com/8397034/28083867-13af2166-6634-11e7-9667-9119c51ca9d0.png)

**Comment by evanweaver** [comment]
@MatthewSteen thanks, I'll add ach.

**Comment by evanweaver** [comment]
Fixed via https://www.pivotaltracker.com/n/projects/2054065/stories/149191479
