### ISSUE TITLE
Not able to Load Dview

### ISSUE THREAD

**Issue by rwadhwa910** [NREL/wex#109]
I am not able to use Dview as when I try to open the Dview with Openstudio, It gives me the error following units failed to load.

Also, I am not able to use Dview as a standalone app.
 
Current OS Windows 10

OS APP 1.0.1
OS  3.0.1

![error](https://user-images.githubusercontent.com/63880759/89826560-a528d680-db13-11ea-91b7-f4e0905aa916.PNG)

**Comment by michaelsweeney** [comment]
shameless plug: you can try using [Timestep ](https://michaelsweeney.github.io/timestep/) instead of Dview.
