### ISSUE TITLE
Dview compiled version

### ISSUE THREAD

**Issue by vsotofrances** [NREL/wex#114]
Dear developers,
Dview is no available in its compiled version ( for windows).
Would it be possible to have in tags a zip with the compiled version?
Is not necessary to have the latest version. I was using the link for my students.

Thanks in advance
Victor

**Comment by janinefreeman** [comment]
Hi Victor- apologies for removing the compiled windows version. The DView page has been updated (https://github.com/NREL/wex/wiki/DView) and the release for windows is tagged: (https://github.com/NREL/wex/releases/tag/v1.2.0)
