### ISSUE TITLE
Download and install Dview 

### ISSUE THREAD

**Issue by Djiben** [NREL/wex#137]
How do I download and install Dview for windows? I can't find a link !

**Comment by aowabinr** [comment]
Seems like the standalone installer link isn't working. https://github.com/NREL/wex/releases/tag/v1.2.0

**Comment by Sigmoidas** [comment]
And older DView 1.0.0 version is available for download here: https://github.com/NREL/wex/releases/tag/v1.0.0
It opens up and works fine on Windows 10.0.19044 Build 19044

**Comment by macumber** [comment]
Hmm that v1.0.0 release is not available anymore.  @sjanzou @shorowit are the DView installers being taken down on purpose?

**Comment by sjanzou** [comment]
> Hmm that v1.0.0 release is not available anymore. @sjanzou @shorowit are the DView installers being taken down on purpose?

all the wex releases are available (without signing into GitHub) at: 
https://github.com/NREL/wex/releases

Specific links for 
DView 1.0.0 
https://github.com/NREL/wex/releases/tag/v1.0.0

 and DView 1.2.0
https://github.com/NREL/wex/releases/tag/v1.2.0

Let us know if you have any issue accessing the links above.

GitHub likes to change all of the previous releases to draft when we make a new release of wex.

We should make a separate repo for DView if this continues to be an issue,

**Comment by shorowit** [comment]
Aside from the installers being public on GitHub again, I'm going to post them on the BEopt website. Perhaps the OS App team would like to post them on their website too.

**Comment by macumber** [comment]
Thanks @sjanzou and @shorowit, the links are working now.  Last night they went to the GitHub error page. My guess is that the 1.0.0 and 1.2.0 releases are getting hidden because they are tagged as pre-releases.  Possibly GitHub thinks that users don't care about pre-releases after a new release is issued? Would you be able to convert the 1.0.0 and 1.2.0 releases to real releases?

**Comment by sjanzou** [comment]
> Thanks @sjanzou and @shorowit, the links are working now. Last night they went to the GitHub error page. My guess is that the 1.0.0 and 1.2.0 releases are getting hidden because they are tagged as pre-releases. Possibly GitHub thinks that users don't care about pre-releases after a new release is issued? Would you be able to convert the 1.0.0 and 1.2.0 releases to real releases?

@shorowit is going to host the DView release on the BeOpt site to prevent this issue with future releases.

**Comment by shorowit** [comment]
DView installers are now available on the [BEopt website](https://www.nrel.gov/buildings/beopt.html).
