### ISSUE TITLE
CLI documentation

### ISSUE THREAD

**Issue by wta12** [NREL/wex#14]
Currently, Dview always checks the first variable in list (often datetime columns) although I specified by **/i** and **/v** is unable to open by columns name as described in help file. Could I got of some command samples for open Dview in CLI ?
`dviewx64 /i 13 /i 17  run_0.csv
`![image](https://user-images.githubusercontent.com/16380735/28151214-e4a40ac2-675e-11e7-87cb-c4a2b676c7c4.png)
`dviewx64 /v "LOADPROFILE_PLANT:Plant Load Profile Mass Flow Rate [kg/s](TimeStep)" run_0.csv`
![image](https://user-images.githubusercontent.com/16380735/28151329-a028357a-675f-11e7-81d0-88433e4e45cf.png)
[csv.zip](https://github.com/NREL/wex/files/1144123/csv.zip)

**Comment by nickdiorio** [comment]
@wta12, Our sincere apologies for the delay, we will work on posting some documentation for the CLI.

**Comment by nickdiorio** [comment]
I've added documentation to: https://github.com/NREL/wex/wiki/Command-Line-Interface on how to use the command line interface.  Of note, support for multiple column plotting on the initial opening of a file does not appear to be functional at this time.  I'll open an issue for that.

Also the `-i` option only offers to plotting one initial column by index.

**Comment by nickdiorio** [comment]
Opened Issue 9

**Comment by shorowit** [comment]
@wta12 Note that the variable shows up differently in DView than what's specified in the csv file. Apparently DView is detecting the units and automatically appending them at the end. This worked for me:
`dview /v "LOADPROFILE_PLANT:Plant Load Profile Mass Flow Rate (TimeStep) (kg/s)" run_0.csv`

**Comment by shorowit** [comment]
You can specify multiple variables like this:
`dview /v "LOADPROFILE_PLANT:Plant Load Profile Mass Flow Rate (TimeStep) (kg/s),LOADPROFILE_PLANT:Plant Load Profile Heat Transfer Rate (TimeStep) (W)" run_0.csv`

**Comment by wta12** [comment]
@shorowit: There are still some scenarios were not covered : 
1. Open in multi variables in one files in different charts (top and bottom)
2. Open multi variables from different files in different charts
Regards.
