### ISSUE TITLE
Command line interface -v option not supporting multiple inputs

### ISSUE THREAD

**Issue by nickdiorio** [NREL/wex#38]
When trying to open DView with more than one column initially plotted using the `-v` option, only the last specified option gets plotted.

As example using [test.csv](files/test.csv)
`dview \v "Beam (W/m2)", \v "Diffuse (W/m2)" test.csv`

Only the "Diffuse" column gets plotting initially.

**Comment by shorowit** [comment]
I can't access the test.csv file, but it should be:
`dview /v "Beam (W/m2),Diffuse (W/m2)" test.csv`

**Comment by nickdiorio** [comment]
Thanks @shorowit , I verified that works.  I had a space after the comma that was resulting in "Diffuse" not opening.  I've updated the wiki.
