### ISSUE TITLE
Support for missing values?

### ISSUE THREAD

**Issue by shorowit** [NREL/wex#41]
Requested at https://beopt.nrel.gov/node/950

> I am investigating using DView to view time-series of air-pollution and meteorological data. Great software!
Is there any way to represent missing values?
An "empty" values (ie , ,) results in the remainder of the time-series being "shuffled" forward in time to cover the missing values, breaking the temporal consistency with other series. I would consider this a bug.
An invalid value (eg X, NaN) results in a zero. This is a problem for variables for which zero is a valid value (eg temperature), and it also corrupts the daily averages.
Setting to -999 and then manually setting the minimum range results in near-vertical lines (down the the bottom of the panel) and is not very elegant.
Any suggestions? The preferred functionality would be to simply have a break in the line when there is missing data.

**Comment by nickdiorio** [comment]
I will take a look at the options we have for handling this data.  The best option may be to alert the user that there is missing data and require them to make their own approximation (0 out Nan's, or interpolate between nearest neighbors).  If it is possible to implement the preferred functionality easily, than we will do that.
