### ISSUE TITLE
Unit Conversion Error: kgWater/kgDryAir

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/wex#43]
Encounter this error after requesting the following Cooling Coil OutputVariables from OpenStudio.

>Output:Variable,*,Cooling Coil Air Inlet Humidity Ratio,hourly; !- HVAC Average [kgWater/kgDryAir]
Output:Variable,*,Cooling Coil Air Outlet Humidity Ratio,hourly; !- HVAC Average [kgWater/kgDryAir]

![image](https://user-images.githubusercontent.com/8397034/33357814-01c2e322-d482-11e7-8f61-b2387101ea47.png)

**Comment by nickdiorio** [comment]
Fixed in f03c19f74457c269e074f306c430599d6d35be42, thanks for letting us know!

**Comment by eringold** [comment]
Shouldn't the conversion factor for humidity ratio (mass/mass) be 1? 

https://github.com/NREL/wex/blob/develop/src/dview/dvfilereader.cpp#L1587
