### ISSUE TITLE
Qt WebEngine problems on Ubuntu preclude ResultsViewer (OS 2.2.1) and DView (OS 2.2.2) from running on Ubuntu

### ISSUE THREAD

**Issue by evanweaver** [NREL/wex#59]
_From @evanweaver on September 13, 2017 15:34_

ResultsViewer call stack on Ubuntu 14.4

bldadmin@ubuntu:~$ cd /usr/bin/
bldadmin@ubuntu:/usr/bin$ ./OpenStudioApp
REQUEST REFRESHALL CALLED 
 REFRESHALL CALLED 
 DO REFRESH CALLED 0
[0913/093230:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
[0913/093230:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
/usr/bin/ResultsViewer: error while loading shared libraries: libqwt.so: cannot open shared object file: No such file or directory

_Copied from original issue: NREL/OpenStudio#2777_

**Comment by evanweaver** [comment]
We should verify that DView starts on Ubuntu.

**Comment by evanweaver** [comment]
DView call stack on Ubuntu 14.4


Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
[0913/132859:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
/usr/bin/DView: error while loading shared libraries: libwx_baseu_net-3.0.so.0: cannot open shared object file: No such file or directory

**Comment by evanweaver** [comment]
_From @macumber on September 13, 2017 20:55_

Why is DView invoking WebEngine?  Does it include a web browser?

**Comment by evanweaver** [comment]
_From @macumber on September 13, 2017 21:0_

Oh I see, you are starting the app and then launching it?

**Comment by evanweaver** [comment]
Yep

**Comment by evanweaver** [comment]
_From @macumber on September 13, 2017 21:15_

Cool, the WebEngine errors are not related to why the apps are failing.  Only the last messages about 

    /usr/bin/DView: error while loading shared libraries: libwx_baseu_net-3.0.so.0: cannot open shared object file: No such file or directory

are relevant.  You should be able to replicate by just running

    /usr/bin/DView

Does that have the same issue?  If not, then something the app is doing is messing with the environment.

**Comment by evanweaver** [comment]
_From @eshadd on September 13, 2017 22:46_

Also noticed that Geometry tab makes OS close. Possibly same Dview issue?

**Comment by evanweaver** [comment]
_From @macumber on September 14, 2017 0:8_

What operating system are you using @eshadd?  If Windows, I suspect your issue is related to https://github.com/NREL/OpenStudio/issues/2604 rather than this one

**Comment by evanweaver** [comment]
_From @macumber on September 14, 2017 0:19_

For this issue we just need to statically link the wx libraries or ship shared object libraries on Linux

**Comment by evanweaver** [comment]
_From @eshadd on September 15, 2017 6:3_

@macumber I'm using Linux.

**Comment by jmarrec** [comment]
Dview loads fine on Ubuntu 16.04, tested with current OpenStudio develop that I built

**Comment by evanweaver** [comment]
@jmarrec yes I fixed this previously and this ticket should be closed. Thanks for the reminder.

**Comment by jmarrec** [comment]
@evanweaver do you recall how you fixed this? I'm getting pretty much the same error using OS App on Ubuntu 16.04
