### ISSUE TITLE
Unable to start DView on Windows

### ISSUE THREAD

**Issue by shorowit** [NREL/wex#62]
Forwarded from https://beopt.nrel.gov/node/962

"The application was unable to start correctly (0xc000007b). Click OK to close the application."

Previous versions of DView worked for them.

**Comment by evanweaver** [comment]
@shorowit do you know which version of DView is included with BEopt 2.8.0.0?

**Comment by shorowit** [comment]
@evanweaver Yes, it was https://github.com/NREL/wex/releases/tag/v1.0.0

**Comment by nickdiorio** [comment]
Based on the thread: https://beopt.nrel.gov/node/962, was this identified to be an issue with DView, or another software package?  If it is DView, can someone attach an example data file upon which DView cannot open?

**Comment by shorowit** [comment]
It is indeed an issue with the DView installation package linked above. The user told me that the error occurs even when launching the program without any data file. 

When I created the previous packages of DView for Windows, which work for this user, I included msvcp120.dll and msvcr120.dll. The package above has no extra dlls included with it though. Could that be the problem?

**Comment by nickdiorio** [comment]
When I've previously seen: "The application was unable to start correctly (0xc000007b). Click OK to close the application.", it was indeed due to missing dll dependencies.  I'm not specifically aware that DView depends on those dll's, but it sounds like it's worth a shot to try.

**Comment by shorowit** [comment]
Well, I should have clarified that we still ship those dlls with BEopt, so when the user tried launching the DView included with BEopt, it was tested with those dlls. But I thought maybe there is a new dll dependency? Or newer versions of those dlls are required?

**Comment by nickdiorio** [comment]
Looking at the dependencies of DView, I don't believe there are any non-system level dll dependencies.  
![image](https://user-images.githubusercontent.com/5658281/35996897-0889d9dc-0cd5-11e8-8b25-67a30e43f1a0.png)
Traditionally the DView.exe has been been downloadable without requiring packaging in of third-party libraries, so I'm not quite sure what is going on.  We can keep investigating

**Comment by shorowit** [comment]
Hmm. Aron said the msvcp and msvcr dlls were needed. And I personally recall past attempts to use DView with errors until I had these dlls.

**Comment by nickdiorio** [comment]
Yes I think msvcp is indeed required.  The main question is how to determine which is the offending dll.  Possibly the version of the dll was updated and the user's version is out of date.  I'll look at how they can troubleshoot more.

**Comment by nickdiorio** [comment]
The most likely cause of this is that there are 64-bit dlls expected and 32-bit dlls being loaded in (or vice versa).  We need to more clearly delineate the version of the exe which we provide.

**Comment by nickdiorio** [comment]
After contact with the user, they have found a work-around to their issue.  I believe the issue is caused due to the user not having a version of msvcr.dll.  For future users, I'd recommend these resources:

https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install-winpc/msvcr120dll-missing/ef3bca56-3155-4383-ac99-d2a6ea262831?auth=1

 https://www.drivereasy.com/knowledge/how-to-fix-the-application-is-unable-to-start-correctly-0xc00007b-error/

**Comment by shorowit** [comment]
Err... so are we planning to update the package to include the needed dll(s)? A user shouldn't have to manually do this.

**Comment by nickdiorio** [comment]
I don't know.  It doesn't appear to me that we've ever done this for DView.  Right now you download the .exe and we assume the user has all required dll's.   Another approach would be to write a more custom installer that installs DView into Program Files and unpackages the appropriate redistributed C++ libraries.  We can certainly discuss doing that, but it will fundamentally shift the existing paradigm.  @evanweaver , do you have any additional thoughts?

**Comment by shorowit** [comment]
As I said earlier: "When I created the previous packages of DView for Windows, which work for this user, I included msvcp120.dll and msvcr120.dll". As far as I know, all we need at a minimum is a zip file for Windows that includes the exe and the appropriate dlls alongside it.

**Comment by evanweaver** [comment]
We, in the land of OpenStudio, include those dlls as well.

**Comment by nickdiorio** [comment]
Ok, great.  Well an easy solution would then be to package the .exe in a zip file with the required .dll's.  That should be pretty easy.

**Comment by shorowit** [comment]
For what it's worth, I got confirmation that using 64-bit dlls fixed the problem for one of our users.

**Comment by nickdiorio** [comment]
That's good.  I've been meaning to rebuild and include the dlls.  I will make it a priority.

**Comment by nickdiorio** [comment]
@shorowit , updated here: https://github.com/NREL/wex/releases/tag/v1.0.0 .  I created a folder with some visual c++ dlls.  Hopefully that covers the issues.
