### ISSUE TITLE
Disable stacked area by default

### ISSUE THREAD

**Issue by shorowit** [NREL/wex#65]
I noticed that the DView shipped with OS 2.4.0 has "Stacked area on left Y axis" checked by default. I strongly think it should be unchecked by default, which was the default behavior in every previous version of DView and, I think, the expected behavior by most users. Furthermore, the stacked view has some really bad limitations -- for example, if I load 8760 hourly data from EnergyPlus, it simply tells me "too many data points: please zoom in" so I can't even view the data.

**Comment by jmarrec** [comment]
I was confused by this behavior too. It seems though that DView seems to remember your preferences from one session to the next, so worst case you have to go to each tab once to turn stacking off, and upon subsequent sessions it'll use a line instead of a stacked area.

**Comment by jmarrec** [comment]
Ok I found where that is really happening, fixed it in #73
