### ISSUE TITLE
DView crashes when opening E+ 8.9 SQL with timeseries with Annual reporting 

### ISSUE THREAD

**Issue by macumber** [NREL/wex#66]

**Comment by macumber** [comment]
Example SQL files are included here https://github.com/NREL/EnergyPlus/pull/6456

Documentation of changes here https://github.com/NREL/EnergyPlus/pull/6483

**Comment by evanweaver** [comment]
Reference https://github.com/NREL/wex/pull/68

**Comment by macumber** [comment]
Doesn't crash but also doesn't show anything useful
