### ISSUE TITLE
Unit Conversion Error: W/W

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/wex#87]
When requesting OutputVariables from OpenStudio 2.7.0 for COPs (e.g. `Chiller COP`).

**Comment by nickdiorio** [comment]
This is an issue primarily with an implementation built for Open Studio.  At this time, we would request Open Studio users or developers address this problem and submit a pull request.

**Comment by nickdiorio** [comment]
Please also see the related issue https://github.com/NREL/wex/issues/69 for a detailed description of what this is, and a commit example for how to fix it.
